### ISSUE TITLE
Auto-refresh when images are updated?

### ISSUE THREAD

**Issue by jtuliani** [shd101wyy/vscode-markdown-preview-enhanced#120]
Where an image is embedded, it would be great if the preview would auto-refresh any time the underlying image file is updated.

**Comment by kachkaev** [comment]
Hi @jtuliani 👋 

It's unfortunate that both locally stored and remote images do not have any API that would report a change – otherwise this feature would be doable. The only alternative that our world provides is to continuously send lots of requests to all images on the page to not miss an update, but this would kill the plugin performance for may users.

You can manually refresh an image by appending `?something-useless` to its url, e.g.:

```
![img](path/to/image.png)
![img](path/to/image.png?abc)
![img](path/to/image.png?abcd)
```

These changes in image URI will trigger a refetch, but will request an image from the same location. Consequently, it will update if it has been changed on the disk or on a server. Hope this helps.

**Comment by jtuliani** [comment]
Thanks for the response. Pity. Even if it was local only (and there is an API to notify changes in that case, on Windows at least, I believe), that would be a major plus.
