### ISSUE TITLE
不能使用[TOC]生成目录

### ISSUE THREAD

**Issue by EterNalGT** [shd101wyy/vscode-markdown-preview-enhanced#1825]
不知道你是不是国人
看名字拼写有点像
所以决定用中文来提
10月10日更新了版本之后
发现用[TOC]不能生成目录了
预览界面只剩下[CROSSNOTETOC]
所以特地问下现在是有别的方法生成目录么
还是必须要自己写了

**Comment by shd101wyy** [comment]
你 `[TOC]` 上下加空行试试？

```

[TOC]

```

还不行的话你得发我一个 markdown 文件。要不然我不知道怎么出的错嗷。

**Comment by shd101wyy** [comment]
应该已经修复了

**Comment by EterNalGT** [comment]
谢了
哥们

**Comment by jwgarrett** [comment]
@shd101wyy Would you please add the ability for [[_TOC_]] to render in preview just like [TOC] does? It is the Azure DevOps github markdown. Look at the screenshot because the under scores are being linted from this comment :-(
![103890374-dcf67300-50df-11eb-911e-43885239ca67](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/4183972/2a267ca6-3527-48d0-81df-d6514345a9b3)
![103890298-b46e7900-50df-11eb-9fc1-ae203970015b](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/4183972/565fe010-67b8-4da2-b5ff-0ac204759ec6)
