### ISSUE TITLE
mindmap with markmap.js

### ISSUE THREAD

**Issue by StefanoCecere** [shd101wyy/vscode-markdown-preview-enhanced#394]
i read the Mermaid is working on mindmaps.. but it is at early stages.
a working (and beautiful!) solution in JS is https://markmap.js.org/

could it be a viable solution to embed?

**Comment by shd101wyy** [comment]
Yes it could be possible. I will take a closer look at markmap.js. Thanks!

**Comment by DonaldTsang** [comment]
Any updates on this one? Since Mermaid is good

**Comment by heartacker** [comment]
hope that we can enjoy markmap as  seem as possible

**Comment by HaibaraMegumi** [comment]
markmap  could be used  now?

**Comment by leolcao** [comment]
For the current version 0.6.8, still not support to render the mindmaps from mermaid block in markdown, but the VSCode builtin markdown previewer support it with the extension bierner.markdown-mermaid~

**Comment by shd101wyy** [comment]
@leolcao Mindmap is now supported in mermaid now in the latest `0.6.10` version.  
So I am closing this issue. Thank you!

**Comment by leolcao** [comment]
Thanks and now it works in new version.,

Btw, I tested all charts from from Mermaid.js(10.3.1), and found ZenUML sequence chart is not works in this extension, I guess because it needs additional library from https://mermaid.js.org/syntax/zenuml.html#integrating-with-your-library-website

Any way, this extension is already awesome~

**Comment by shd101wyy** [comment]
The mermaid zenuml will be supported once this PR gets done: https://github.com/shd101wyy/mume/pull/297

**Comment by leolcao** [comment]
Verified and thanks~
