### ISSUE TITLE
Plantuml rendering error caused by version 0.5.14

### ISSUE THREAD

**Issue by JingDeZhe** [shd101wyy/vscode-markdown-preview-enhanced#443]
After updating the 0.5.14 version, plantuml will not be able to render and will report an error. It can be rendered normally in the .pu file

`An error has occured : java.lang.IllegalArgumentException: source is null
Tu l'as trouve ou celui-la ?`

If you go back to the previous version, you can render normally

**Comment by monkeyde17** [comment]
I have same problem at the 0.5.14 version.

## sample

```plantuml
class Block
{
    +offset:int
    +size:int
    +cap:int
    +index:int
    +isuse:bool
}

class DescInfo
{
    +size:int
    +count:int
}
```

## error
An error has occured : java.lang.IllegalArgumentException: source is null
Anything else but the basement that'll keep this elevator from falling?
Diagram size: 16 lines / 183 characters.
PlantUML (1.2020.26) cannot parse result from dot/GraphViz.
Please go to https://plantuml.com/graphviz-dot to check your GraphViz version.
Java Runtime: Java(TM) SE Runtime Environment
JVM: Java HotSpot(TM) Client VM
Default Encoding: UTF-8
Language: zh
Country: CN
PLANTUML_LIMIT_SIZE: 4096
This may be caused by :
- a bug in PlantUML
- a problem in GraphViz
You should send this diagram and this image to
plantuml@gmail.com
or
post to
https://plantuml.com/qa
to solve this issue.
You can try to turn arround this issue by simplifing your diagram.
java.lang.IllegalArgumentException: source is null
net.sourceforge.plantuml.brotli.BrotliInputStream.<init>(BrotliInputStream.java:112)
net.sourceforge.plantuml.brotli.BrotliInputStream.<init>(BrotliInputStream.java:92)
net.sourceforge.plantuml.windowsdot.WindowsDotArchive.extract(WindowsDotArchive.java:76)
net.sourceforge.plantuml.windowsdot.WindowsDotArchive.getWindowsExeLite(WindowsDotArchive.java:95)
net.sourceforge.plantuml.cucadiagram.dot.GraphvizWindowsLite.specificDotExe(GraphvizWindowsLite.java:62)
net.sourceforge.plantuml.cucadiagram.dot.GraphvizWindowsLite.searchDotExe(GraphvizWindowsLite.java:54)
net.sourceforge.plantuml.cucadiagram.dot.AbstractGraphviz.<init>(AbstractGraphviz.java:80)
net.sourceforge.plantuml.cucadiagram.dot.GraphvizWindowsLite.<init>(GraphvizWindowsLite.java:76)
net.sourceforge.plantuml.cucadiagram.dot.GraphvizUtils.create(GraphvizUtils.java:103)
net.sourceforge.plantuml.svek.DotStringFactory.getGraphvizVersionInternal(DotStringFactory.java:291)
net.sourceforge.plantuml.svek.DotStringFactory.getGraphvizVersion(DotStringFactory.java:285)
net.sourceforge.plantuml.svek.GeneralImageBuilder.printEntityInternal(GeneralImageBuilder.java:566)
net.sourceforge.plantuml.svek.GeneralImageBuilder.printEntity(GeneralImageBuilder.java:548)
net.sourceforge.plantuml.svek.GeneralImageBuilder.printEntities(GeneralImageBuilder.java:540)
net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:413)
net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:118)
net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:83)
net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:659)
net.sourceforge.plantuml.classdiagram.ClassDiagram.exportDiagramInternal(ClassDiagram.java:205)
net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:180)
net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:144)
net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:164)
net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:117)
net.sourceforge.plantuml.Run.managePipe(Run.java:379)
net.sourceforge.plantuml.Run.main(Run.java:180)

**Comment by shd101wyy** [comment]
Sure I will take a look when I have time. Thank you for reporting the issue

**Comment by slayercat** [comment]
seems same to me. plantuml will crash sometimes.

![图片](https://user-images.githubusercontent.com/1755442/103344973-15d48d80-4acb-11eb-8063-c521dd8f6366.png)

![图片](https://user-images.githubusercontent.com/1755442/103345020-37ce1000-4acb-11eb-9beb-70c6dc603b39.png)

```

```

**Comment by shd101wyy** [comment]
I just published a new version. Could you guys please try it out? Thank you

**Comment by JingDeZhe** [comment]
After updating to version 0.5.15, the problem has been fixed, praise the author's high efficiency.
