### ISSUE TITLE
FetchError: Cannot follow redirect with body being a readable stream

### ISSUE THREAD

**Issue by anb0s** [shd101wyy/vscode-markdown-preview-enhanced#607]
I try to use plant.uml server and kroki server and see only this error message in the preview:

![image](https://user-images.githubusercontent.com/95811/176995198-d217759c-4c3f-4b42-a352-8fb9e1398cc4.png)

i do not see any further errors from plugin in log view.

how to debug?

**Comment by swordjjjkkk** [comment]
i have same problem ,have you worked out ?

**Comment by anb0s** [comment]
no, i have no clue, it works with other markdown previewers, so we droped this plugin for now :(

**Comment by swordjjjkkk** [comment]
#613 I solved it

**Comment by wchisenski** [comment]
Today, I was setting up a new laptop, and instead of jumping through the Java, Graphviz/PlantUML hoops decided to simply utilize the plantuml-server Docker image and ran across this same error. @shd101wyy it's been almost a year since this issue was identified with #613 providing additional details about updating MUME to resolve the issue.

Is there another problem that's holding up getting this issue resolved? I can't believe there are only a few of us that want to utilize a PlantUML server instead of local installs for the needed requirements.

Any additional thoughts or feedback would be great, thank you!

Walter

**Comment by shd101wyy** [comment]
Just published a new release. Tried locally on my laptop and it's working fine.

**Comment by wchisenski** [comment]
Hi @shd101wyy,

Are you sure it's still not using the installed PlantUML jar file? I've tried both a local Docker instance and simply pointing it to the public PlantUML server on the internet, neither works. I'm still getting the same issue using the latest version.

<img width="528" alt="image" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/53623427/a39cc881-8420-4fcc-b19c-319a280084c3">

<sup>PlantUML Server Setting</sup>

<img width="591" alt="image" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/53623427/80feeb7d-c3b6-4c2e-8bc8-85c60040b411">

<sup>Error</sup>

Otherwise, it's a great extension, but I need to fall back to the built-in Markdown preview and simply utilize the [PlantUML Extension](https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml).

Walter

**Comment by shd101wyy** [comment]
Hi @wchisenski , this is not a valid server I believe.   

Could you please try running the plantuml server using docker like:

```
$ docker run -d -p 8080:8080 plantuml/plantuml-server:jetty
```

Then set the server address to `http://localhost:8080/svg/`.

**Comment by shd101wyy** [comment]
I will take a closer look this week. I am also not sure if `https://www.plantuml.com/plantuml` and `docker run -d -p 8080:8080 plantuml/plantuml-server:jetty` are the same thing or not.

**Comment by shd101wyy** [comment]
Okay @wchisenski I see why. Our code uses the `POST` but the `http://www.plantuml.com/plantuml` server doesn't support the `POST` method. If you try the local server which has `POST` enabled then it should work fine. 

Please make sure you set the server address to `http://localhost:8080/svg/`, not `http://localhost:8080/`

**Comment by shd101wyy** [comment]
Another option is to use the [Kroki](https://kroki.io/) which also supports plantuml. MPE requires some special syntax for it, like below:

````
```plantuml {kroki=true}
A  -> B
```
````

**Comment by wchisenski** [comment]
Hi @shd101wyy,

You've been **very** helpful in getting me over the hump here. I had no idea this extension was attempting an HTTP POST. The URL you provided above `http://localhost:8080/svg/` works perfect with the plantuml-server docker image. I also appreciate the additional information for the public Kroki server as a _fallback_ solution.

Thank you again!

Walter
