### ISSUE TITLE
Don't work to expand variables or ~ in configPath 

### ISSUE THREAD

**Issue by fmsyt** [shd101wyy/vscode-markdown-preview-enhanced#625]
I want to move mume directory in `$HOME/.config/mume`.
But actual created in `%LOCALAPPDATA%\Programs\Microsoft VS Code\$HOME\.config\mume`.

Configured in remoteWSL:

```json
{
    "markdown-preview-enhanced.configPath": "$HOME/.config/mume"
}
```

In default, mume is created in `~/.local/state/mume`

thank you.

**Comment by DoItWithASmile** [comment]
I second that issue.

I came across it while trying to do "${workspaceFolder}/".
I am looking for a per-workspace configuration for the editor. Reason being that each workspace might have their own custom styles. Since MPE doesn't care about VS code's markdown.styles setting, this would be an acceptable workaround.
