### ISSUE TITLE
convert to pdf file, code blocks cannot display long code

### ISSUE THREAD

**Issue by YuanzheTian** [shd101wyy/vscode-markdown-preview-enhanced#630]
convert md to pdf file with Chorme(Puppeteer) -> PDF,

this is my md code:
![image](https://user-images.githubusercontent.com/44792821/198244631-c3eb596b-72a9-487c-9696-f45c659169c9.png)

and this is my perview code:
![image](https://user-images.githubusercontent.com/44792821/198244688-13847a5a-1913-48e0-ad06-dacbb7fc8549.png)

this is my pdf display:
![image](https://user-images.githubusercontent.com/44792821/198244781-128bd0f5-5273-4bd5-8f2c-467d763ea86d.png)
missing following code.

**Comment by Ozurah** [comment]
Hello, I've just encountered this issue and found a workaround.

I added a style when printing :

my markdown `.md` :
```
---
puppeteer:
    format: A4
    printBackground : true
---

@import "path/sample-fix.less" 

```js
var a = "hello world, this is a line with a very long phrase that should be wrapped. I've set js, but it's only to set a language type";
\```

```py
a = 123
print("no slider for this code block")
\```
```
> just remove the "escape \" for code block 

and place the style file according to the import path of your `.less` file
```less
@media print {
    pre[class*="language-"] {
        white-space: initial;
    }
}
```

Remarks :
- If you don't want to add this style to every markdown you made, you can edit the default style file used by `Markdown Preview Enhanced`, at this location `C:\Users\[user]\.mume\style.less` (but it's local)
- The `@media print` is added to keep the horizontal slider of the code block in the preview
- If you prefer `.css` instead of `.less`, you can, but it won't rendered in the preview

![image](https://user-images.githubusercontent.com/80265286/200132627-428886aa-f0e3-4053-be24-52adaf4f5c29.png)

**Comment by Ozurah** [comment]
Hello, I've just encountered this issue and found a workaround.

I added a style when printing :

my markdown `.md` :
```
---
puppeteer:
    format: A4
    printBackground : true
---

@import "path/style.less" 

```js
var a = "hello world, this is a line with a very long phrase that should be wrapped. I've set js, but it's only to set a language type";
\```

```py
a = 123
print("no slider for this code block")
\```
```
> just remove the "escape \" for code block 

and place the style file according to the import path of your `.less` file
```less
@media print {
    pre[class*="language-"] {
        white-space: pre-line;
    }
}
```

Remarks :
- If you don't want to add this style to every markdown you made, you can edit the default style file used by `Markdown Preview Enhanced`, at this location `C:\Users\[user]\.mume\style.less` (but it's local)
- The `@media print` is added to keep the horizontal slider of the code block in the preview
- If you prefer `.css` instead of `.less`, you can, but it won't rendered in the preview

![image](https://user-images.githubusercontent.com/80265286/200133010-daa8598d-a927-418f-8bac-017748f0976f.png)

**Comment by YuanzheTian** [comment]
> Hello, I've just encountered this issue and found a workaround.
> 
> I added a style when printing :
> 
> my markdown `.md` :
> 
> ```
> ---
> puppeteer:
>     format: A4
>     printBackground : true
> ---
> 
> @import "path/style.less" 
> 
> ```js
> var a = "hello world, this is a line with a very long phrase that should be wrapped. I've set js, but it's only to set a language type";
> system.out.println(a);
> \```
> 
> ```py
> a = 123
> print("no slider for this code block")
> \```
> ```
> 
> > just remove the "escape \" for code block
> 
> and place the style file according to the import path of your `.less` file
> 
> ```css-less
> @media print {
>     pre[class*="language-"] {
>         white-space: pre-wrap;
>     }
> }
> ```
> 
> Remarks :
> 
> * If you don't want to add this style to every markdown you made, you can edit the default style file used by `Markdown Preview Enhanced`, at this location `C:\Users\[user]\.mume\style.less` (but it's local)
> * The `@media print` is added to keep the horizontal slider of the code block in the preview
> * If you prefer `.css` instead of `.less`, you can, but it won't rendered in the preview
> 
> ![image](https://user-images.githubusercontent.com/80265286/200133304-bb040e6c-1613-4191-8320-e3a79bee83e0.png)
> 
> _edition : use `pre-wrap` instead of `initial`, otherwise the second line will not go to the line. `pre-line` will remove code indentation_



> Hello, I've just encountered this issue and found a workaround.
> 
> I added a style when printing :
> 
> my markdown `.md` :
> 
> ```
> ---
> puppeteer:
>     format: A4
>     printBackground : true
> ---
> 
> @import "path/style.less" 
> 
> ```js
> var a = "hello world, this is a line with a very long phrase that should be wrapped. I've set js, but it's only to set a language type";
> system.out.println(a);
> \```
> 
> ```py
> a = 123
> print("no slider for this code block")
> \```
> ```
> 
> > just remove the "escape \" for code block
> 
> and place the style file according to the import path of your `.less` file
> 
> ```css-less
> @media print {
>     pre[class*="language-"] {
>         white-space: pre-wrap;
>     }
> }
> ```
> 
> Remarks :
> 
> * If you don't want to add this style to every markdown you made, you can edit the default style file used by `Markdown Preview Enhanced`, at this location `C:\Users\[user]\.mume\style.less` (but it's local)
> * The `@media print` is added to keep the horizontal slider of the code block in the preview
> * If you prefer `.css` instead of `.less`, you can, but it won't rendered in the preview
> 
> ![image](https://user-images.githubusercontent.com/80265286/200133304-bb040e6c-1613-4191-8320-e3a79bee83e0.png)
> 
> _edition : use `pre-wrap` instead of `initial`, otherwise the second line will not go to the line. `pre-line` will remove code indentation_

its cool, solved my problems，and it is still a bit troublesome to always add a style.less file. It's acceptable.thanks
